sudo: required
dist: trusty
language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: "18"
    - node_js: "16"
    - node_js: "14"
    - node_js: "13"
    - node_js: "12.3"
    - node_js: "10.17"
services:
  - cassandra
